### ISSUE TITLE
Pseudocode Issue

### ISSUE THREAD

**Issue by jeffreyrusovskiy** [angela1465/georgia#2]
In your fourth line, you write: 

> If maze isn't navigable, return false.

This seems a bit shaky—you are assessing whether the maze is navigable directly in the base case checks. What does this mean? Are you checking to see whether there is no treasure?

It may also be beneficial to address what should occur if the explorer initiates travel from a space that has a wall on it directly inside your base case checks.

**Comment by GraceFeeley** [comment]
Thank you for your feedback! I will begin to edit right away.
--Grace
